sudo: false
dist: trusty
services:
  - docker
language: node_js

node_js:
  - "10.12.0"

install:
  - yarn

script:
  - yarn test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t artecher/mock-console-web-server:latest .
  - docker push artecher/mock-console-web-server:latest