apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-console-web
  template:
    metadata:
      labels:
        app: mock-console-web
    spec:
      containers:
        - name: mock-console-web-server
          image: artecher/mock-console-web-server:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongo-cluster-ip
            - name: MONGO_PORT
              value: '27017'